apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextappservice-deployment
  labels:
    app: nextappservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextappservice
  template:
    metadata:
      labels:
        app: nextappservice
    spec:
      containers:
        - name: nextappservice
          image: it21177828/nextappservice:latest
          ports:
            - containerPort: 3000
              hostPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-url

---
apiVersion: v1
kind: Service
metadata:
  name: nextappservice-service
spec:
  type: NodePort
  selector:
    app: nextappservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30011



