apiVersion: v1
kind: Secret
metadata:
  name: course-secret
type: Opaque
stringData:
  db-url: "mysql://admin:12345678@sa-db.crq2swewae5v.us-east-1.rds.amazonaws.com:3306/lms" # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth