apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseservice-deployment
  labels:
    app: courseservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courseservice
  template:
    metadata:
      labels:
        app: courseservice
    spec:
      containers:
      - name: courseservice
        image: it21177828/courseservice:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: course-secret
              key: db-url

---
apiVersion: v1
kind: Service
metadata:
  name: courseservice-service
spec:
  type: NodePort
  selector:
    app: courseservice
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
    